name: auto_gallery
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  easy_folder_picker: ^1.1.1
  flutter:
    sdk: flutter
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  image_picker: ^0.8.3
  path_provider: ^2.0.2
  share_plus: ^2.1.4
  shared_preferences: ^2.0.6
  store_redirect: ^2.0.0
  url_launcher: ^6.0.9

dev_dependencies:
  build_runner: ^2.1.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  lint: ^1.5.3

flutter:

  uses-material-design: true

  assets:
    - assets/Empty.gif
    - assets/expired.png
    - assets/easter.png

  fonts:
     - family: Berky
       fonts:
         - asset: fonts/berkshire.ttf
     - family: Monty
       fonts:
         - asset: fonts/monty_reg.ttf
         - asset: fonts/monty_semi.ttf
           weight: 600